### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by Cpavrai** [InseeFrLab/InspaCy-UI#15]
In the result screen, add a button `Export the selected entities` in the end of the "Entities list" block, for exporting these selected entities to an endpoint, formatted in JSON.

This button would be enabled only when atleast one entity would be selected.

**Comment by JulietteS** [comment]
It's likely to be just a download in web client. 
JSon must contain : 
* long definition (/concepts/definition/[conceptID]/definition/v1/fr)
* short definition (if available /concepts/definition/[conceptID]/definitionCourte/v1/fr)
* last change on the concept

**Comment by Cpavrai** [comment]
Merged #21
